services:
  cloakr:
    image: haugene/transmission-openvpn:latest
    container_name: cloakr
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - "9091:9091"
    environment:
      OPENVPN_PROVIDER: NORDVPN
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      NORDVPN_COUNTRY: US
      NORDVPN_PROTOCOL: TCP
      LOCAL_NETWORK: 10.69.0.0/16
      TZ: America/Denver
      PUID: "568"
      PGID: "568"
      TRANSMISSION_DOWNLOAD_DIR: /downloads
      TRANSMISSION_INCOMPLETE_DIR: /data/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      TRANSMISSION_WATCH_DIR_FORCE_GENERIC: "true"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - downloads:/downloads
      - watch:/data/watch

volumes:
  downloads:
  watch:
